- name: "Update apt packages."
  become: true
  apt:
    update_cache: yes

- name: "Upgrade packages"
  become: true
  apt:
    upgrade: yes

- name: "Install NodeJS and NPM "
  become: true
  apt:
    name: ["nodejs", "npm"]
    state: latest
    update_cache: yes

- name: "Install pm2"
  become: true
  npm:
    name: pm2
    registry: https://registry.npmjs.com/
    global: yes
    production: yes
    state: present