- name: "Install NodeJS and NPM "
  become: true
  apt:
    name: ["nodejs", "npm"]
    state: latest
    update_cache: yes

- name: "Install pm2"
  become: true
  npm:
    name: pm2
    global: yes
    production: yes
    state: present

- name: Copying the articfact from local to EC2
  become: true
  copy:
    src: /root/project/artifact.tar.gz
    dest: /home/ec2-user/


- name: Uncompress Backend
  become: true
  shell: |
    cd /home/ec2-user
    tar xvzf artifact.tar.gz -C .
    
- name: Starting the app
  become: true
  shell: |
    cd /home/ec2-user
    npm install
    pm2 stop default
    pm2 start npm -- start